name: Collective loop
favicon: null
layout_spectrum: 0.06226
typography_spectrum: 0.7890081568621099
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#10181f'
    - '#c4bec3'
    - '#886a5d'
    - '#a28f86'
  brandStrength: 0.3125
  lightness: 0.8762485045008361
  saturation: 0.0625
  rhythmicContrast: 0.784312543226406
purpose: []
